spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为
      primary: user
      #严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        user:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.99.49.255:3307/mybatis_plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
          username: root
          password: hb742608
        product:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.99.49.255:3307/mybatis_plus_1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
          username: root
          password: hb742608




# Mybatis.yml
mybatis-plus:
  configuration:
    # Service??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ??MyBatis-Plus?????
      id-type: auto
      #??MyBatis-Plus????????
      #table-prefix: t_

  type-aliases-package: top.hanbing777.pojo
  type-enums-package: top.hanbing777.enums



